- doc/README.md
- src/datadog/collector.h
- src/datadog/datadog_agent.cpp
- src/datadog/datadog_agent.h
- src/datadog/environment.cpp
- src/datadog/environment.h
- src/datadog/logger.h
- src/datadog/null_collector.cpp
- src/datadog/null_collector.h
- src/datadog/parse_util.h
- src/datadog/propagation_styles.cpp
- src/datadog/propagation_styles.h
- src/datadog/span_defaults.cpp
- src/datadog/span_defaults.h
- src/datadog/span_sampler.cpp
- src/datadog/span_sampler.h
- src/datadog/span_sampler_config.cpp
- src/datadog/span_sampler_config.h
- src/datadog/trace_sampler.cpp
- src/datadog/trace_sampler.h
- src/datadog/trace_sampler_config.cpp
- src/datadog/trace_sampler_config.h
- src/datadog/trace_segment.h
- src/datadog/tracer.cpp
- test/mocks/collectors.cpp
- test/mocks/collectors.h
- test/span_sampler.cpp
- test/trace_segment.cpp
This took a lot more code than I expected.
The benefit is now we get startup logging like this:
```text
DATADOG TRACER CONFIGURATION - {"collector":{"config":{"event_scheduler_typeid":"N7datadog7tracing22ThreadedEventSchedulerE","flush_interval_milliseconds":2000,"http_client_typeid":"N7datadog7tracing4CurlE","url":"http://localhost:8126/v0.4/traces"},"type":"DatadogAgent"},"defaults":{"environment":"dev","service":"dd-trace-cpp-example","service_type":"web"},"environment_variables":{"DD_TRACE_SAMPLE_RATE":"1"},"extraction_styles":["datadog"],"injection_styles":["datadog"],"span_sampler":{"rules":[]},"tags_header_size":512,"trace_sampler":{"max_per_second":200.0,"rules":[{"name":"*","resource":"*","sample_rate":1.0,"service":"*"}]},"version":"0.0.0"}
```
i.e.
```json
{
"collector": { …
```
> print configuration as JSON on Tracer startup

- src/datadog/clock.h
- src/datadog/span_data.cpp
Envoy's CI reveals yet more shortcomings in this code.
One of these points was already addressed in the not-yet-merged https://github.com/DataDog/dd-trace-cpp/pull/6.
> numeric type portability

- .circleci/config.yml
- Dockerfile
- bin/install-lcov
- bin/publish-coverage
- bin/test
Have CircleCI generate a coverage report and push it to (a newly create repository) `dd-trace-cpp-coverage`. `dd-trace-cpp-coverage` hosts the coverage reports via GitHub Pages.
> Store coverage reports in a website

- CMakeLists.txt
- src/datadog/curl.cpp
- src/datadog/curl.h
- test/CMakeLists.txt
- test/test.cpp
- test/test.h
- test/test_curl.cpp
Envoy doesn't use `class Curl`, but `nginx-datadog` probably will.
This was one of the least tested components of the library.
> Add some unit tests for `class Curl`.

- src/datadog/tracer_config.h
- test/test_tracer_config.cpp
This should have been part of https://github.com/DataDog/dd-trace-cpp/pull/13. My mistake.
> change default propagation styles to begin with W3C

- src/datadog/span.cpp
- src/datadog/span.h
- test/test_span.cpp
Envoy is being modified to use `dd-trace-cpp` in place of `dd-opentracing-cpp`.
The lower level Datadog tracing components within Envoy can use a mock `Collector` to inspect span data. However, the higher level components do not allow for the injection of a `Collector` (part of their role is to specify the `Collector`). They have access to the `datadog::tracing::Span`, though, so let's make that object easier to inspect.
> more Span accessors, for use in Envoy's unit tests

- src/datadog/trace_id.cpp
- src/datadog/trace_id.h
- test/test_trace_id.cpp
`trace_id == some_int` was defined, but not `some_int == trace_id`.
> add missing overloads to TraceID's operator== and operator!=

- .circleci/config.yml
- CMakeLists.txt
- Dockerfile
- test/test_tracer_config.cpp
When building with libc++, as opposed to libstdc++, `operator>>(istream&, double&)` accepts "inf" for infinity and "nan" for NaN. Account for this in some unit tests.
This also modifies the build to use libc++ whenever clang++ is the compiler, instead of the ubuntu default of libstdc++. This required some tweaks to the CI due to a bug in how ubuntu packages clang and libc++.
> Allow infinity and NaN to be parsed.

- src/datadog/curl.cpp
- test/test_curl.cpp
See <https://github.com/DataDog/dd-trace-cpp/issues/31>.
In addition to the recommended change, this revision also adds unit tests that verify that a CURL handle, once created, is destroyed.
> prevent leaking of CURL handles

- CMakeLists.txt
I previously made this change to [nginx-datadog][1], which builds dd-trace-cpp as part of its build. I didn't make the corresponding change in dd-trace-cpp itself because the build image that we use for CI isn't based on Alpine, which packages a newer GCC that has this [bug][2].
[1]: https://github.com/DataDog/nginx-datadog
[2]: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108088
> suppress compiler errors stemming from bugged warning

- CMakeLists.txt
- src/datadog/id_generator.cpp
- src/datadog/id_generator.h
- src/datadog/tags.cpp
- src/datadog/tags.h
- src/datadog/tracer.cpp
- src/datadog/w3c_propagation.cpp
- test/test_span.cpp
- test/test_tracer.cpp
These are the changes necessary for dd-trace-cpp to pass applicable test cases in `tests/parametric/test_128_bit_traceids.py` in Datadog's internal shared tests.
See the commit messages for the correspondence with shared tests.
> pass Datadog's internal shared tests for 128-bit trace IDs

- src/datadog/parse_util.cpp
- src/datadog/tracer.cpp
- test/CMakeLists.txt
- test/test_parse_util.cpp
- test/test_tracer.cpp
I missed a spot in https://github.com/DataDog/dd-trace-cpp/pull/41. The integration test's `-k` command line argument, used to select a subset of tests to run, doesn't work the way I thought, so I wasn't running all of the tests.
This revision enforces a fixed length of 16 for the `_dd.p.tid` trace tag, i.e. the 64-bit hex value must be padded with zeroes.
> enforce fixed length of 16 for _dd.p.tid

- examples/hasher/docker-compose.yaml
- examples/http-server/docker-compose.yaml
My docker daemon doesn't run as `root`, it runs as me. One side effect of this is that the socket used to communicate with the daemon is not `/var/run/docker.sock`, but instead `/run/user/1000/docker.sock`. The `DOCKER_HOST` environment variable is accordingly `unix:///run/user/1000/docker.sock`.
- Most of the time, the docker daemon is running locally as root at `/var/run/docker.sock`.
- With rootless docker, the docker daemon is running locally as a non-root user at `/run/user/$(id -u)/docker.sock`.
- With remote docker, the docker daemon is running remotely at endpoint `DOCKER_HOST`.
This arrangement of:
- mounting `/var/run/docker.sock` from the host
- mounting `/run/user` from the host
- forwarding the `DOCKER_HOST` environment variable (if present)
supports all three cases.
In …
> support rootless docker in examples

- src/datadog/datadog_agent.cpp
- test/test_datadog_agent.cpp
- consider exclusively 200 as a success HTTP status
- log an error for successfull HTTP status with an empty body
> update unsuccessful HTTP requests handling (#38)

- .circleci/config.yml
- Dockerfile
Content:
- Build and test the library on ARM64
- Update Dockerfile to download bazelisk for the corresponding architecture
- Use cmake to build the library
Side notes:
- I pushed a multi-platform version of `datadog/docker-library:dd-trace-cpp-ci`. It supports `linux/amd64` and `linux/arm64`
> Add ARM64 support

- src/datadog/curl.cpp
- src/datadog/http_client.h
- test/test_tracer.cpp
- test/test_tracer_telemetry.cpp
There's no need to hold the lock while executing the response handler. It's not an issue today, but it does prevent a handler from submitting another request.
> curl minutiae

- src/datadog/tracer_config.h
- test/test_tracer_config.cpp
From now on, the tracer will generate 128-bit trace IDs.
Remove the option and code related to 64-bit trace IDs.
> Generate 128-bit trace id by default

- .circleci/config.yml
- src/datadog/version.cpp
Configure parametric test to get the cpp tracer in same way as system-tests
Related with system-tests PR: https://github.com/DataDog/system-tests/pull/1983
> Configure parametric test to get the cpp tracer in same way as system-tests

- src/datadog/tracer.cpp
- src/datadog/tracer_config.cpp
- src/datadog/tracer_config.h
- src/datadog/tracer_telemetry.cpp
- src/datadog/tracer_telemetry.h
- test/test_tracer_telemetry.cpp
This PR send a new type of payload `app_integrations_change` to Telemetry v2. This new payload allows use know which integration is using the Tracer.
> Report `integration` and `integration_version` to telemetry

- src/datadog/datadog_agent.cpp
- src/datadog/datadog_agent.h
- src/datadog/remote_config.cpp
- src/datadog/remote_config.h
- src/datadog/tracer.cpp
- src/datadog/tracer.h
- test/test_remote_config.cpp
- test/test_trace_segment.cpp
- test/test_tracer.cpp
I was integrating the recent sampling delegation changes into the corresponding feature branch in nginx-datadog, and got some compiler errors. They're due to other changes on the dd-trace-cpp main branch.
In nginx-datadog, and in Envoy, the `Tracer` is stored as an `Optional<Tracer>`. A `Tracer` instance is then moved into the variable.
Since `Tracer` now has a `ConfigManager` data member, and `ConfigManager` has a `std::mutex` data member, `Tracer` can no longer be moved (because `std::mutex` cannot be moved).
One thing I could do is use `Optional::emplace` to construct the `Tracer` in place: no move required.
Another thing I could do is make the `Tracer`'s `ConfigManager` a `std::unique_ptr`, so that move semantics are preserved.
Yet another thing I could do is use a `std::unique_ptr` …
> TraceSegment can outlive Tracer

- Dockerfile
Adds `python` to our CI image.
I recently enforced formating/linting in `nginx-datadog`. They share the same CI image.
> chore-ci: install python3

- src/datadog/config_manager.cpp
- src/datadog/config_manager.h
- src/datadog/config_update.h
- src/datadog/remote_config.cpp
- src/datadog/tracer.cpp
- src/datadog/tracer.h
- test/test_remote_config.cpp
This PR add support for `DD_TAGS` dynamic configuration.
> feat: support DD_TAGS dynamic configuration

- src/datadog/config_manager.cpp
There's a test in nginx-datadog that's sensitive to certain fields in the JSON config dump. Recent modifications to dd-trace-cpp changed the name of one of the fields from "defaults" to "default". This PR puts it back.
> restore "defaults", not "default"

- bin/publish-coverage
GitHub displays the commit author based on the email address named in the commit. Thing is, you can put any email address you want. Could be Linus Torvalds.
This PR changes the coverage bot so that it uses Damien's Datadog email instead of mine.
Example: https://github.com/DataDog/dd-trace-cpp-coverage/commit/a6f8f24fab800558a6d2c8e75a1350c75a80fa7f
> Rename the bot, and add some docs.

- BUILD.bazel
- CMakeLists.txt
- src/datadog/config.h
- src/datadog/config_manager.cpp
- src/datadog/config_manager.h
- src/datadog/config_update.h
- src/datadog/datadog_agent.cpp
- src/datadog/datadog_agent.h
- src/datadog/datadog_agent_config.cpp
- src/datadog/datadog_agent_config.h
- src/datadog/parse_util.cpp
- src/datadog/parse_util.h
- src/datadog/remote_config.cpp
- src/datadog/remote_config.h
- src/datadog/span_sampler_config.cpp
- src/datadog/span_sampler_config.h
- src/datadog/string_util.cpp
- src/datadog/string_util.h
- src/datadog/trace_sampler_config.cpp
- src/datadog/trace_sampler_config.h
- src/datadog/tracer.cpp
- src/datadog/tracer_config.cpp
- src/datadog/tracer_config.h
- src/datadog/tracer_telemetry.cpp
- src/datadog/tracer_telemetry.h
- test/test_datadog_agent.cpp
- test/test_remote_config.cpp
- test/test_smoke.cpp
- test/test_trace_segment.cpp
- test/test_tracer_telemetry.cpp
This PR is second and final part of active configuration. This particular PR report configurations in `app-started` event and also report configuration updates received through Remote Configuration.
> [2/2] feat: active configuration - report configuration to telemetry

- .gitignore
- MODULE.bazel
- extensions.bzl
Bzlmod is the new way to handle external dependencies.
This applies https://bazel.build/external/migration
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
> chore(bazel): add MODULE.bazel files for bzlmod

- test/CMakeLists.txt
- test/system-tests/CMakeLists.txt
- test/system-tests/README.md
- test/system-tests/developer_noise.cpp
- test/system-tests/developer_noise.h
- test/system-tests/main.cpp
- test/system-tests/manual_scheduler.h
- test/system-tests/request_handler.cpp
- test/system-tests/request_handler.h
- test/system-tests/utils.h
I've decided to move the parametric system server closer to the source code. This will allow us to give it the attention it deserves. On the other side, system-tests will only need to focus on obtaining a version of dd-trace-cpp, and they'll always build the corresponding parametric HTTP server.
> chore: add parametric system test server

- src/datadog/curl.cpp
- src/datadog/parse_util.cpp
- src/datadog/parse_util.h
- src/datadog/string_util.cpp
- src/datadog/string_util.h
- test/test_parse_util.cpp
- test/test_tracer_config.cpp
> fix: split DD_TAGS either by space or comma

- src/datadog/span.cpp
- src/datadog/span.h
- src/datadog/span_data.cpp
- test/system-tests/request_handler.cpp
- test/test_span.cpp
Simple PR which introduces the following changes:
- Expose `numeric_tags` through the API, although the new API functions refer to `metrics` for consistency with other tracers (e.g. PHP).
- Allow setting internal tags through the API, this is necessary as `dd-trace-cpp` is used by other internal projects such as ASM.
> Allow setting internal tags and expose numeric tags as metrics

- src/datadog/glob.cpp
- test/test_glob.cpp
Ensure glob matching is case insensitive and add test covering case sensitivity.
> fix: glob matching case sensitivity

- src/datadog/parse_util.h
Since GCC 13, std::uint64_t and friends require an explicit include of `<cstdint>`.
See also https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
> parse_util: include cstdint to fix compilation under GCC 13

- .github/CODEOWNERS
- .github/pull_request_template.md
Adds CODEOWNERS and PR template to this repository
* Automatic assignment of reviewers
*  baseline for PR descriptions
Jira ticket: [APMAPI-60](https://datadoghq.atlassian.net/browse/APMAPI-60)
[APMAPI-60]: https://datadoghq.atlassian.net/browse/APMAPI-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add CODEOWNERS and PR template

- src/datadog/w3c_propagation.cpp
- test/test_tracer.cpp
Usage of std::regex_match was problematic for traceparent with trailing spaces. The overload use is `std::regex_match(str, str + std::char_traits<CharT>::length(str), m, e, flags)`, which resolves as the whole input instead of the trimmed input.
This regression has been introduced in #119 
Changes:
- Fix std::regex_match usage.
- Add unit test.
> fix: regex usage in w3c extraction

- src/datadog/w3c_propagation.cpp
- test/test_tracer.cpp
I clarified a misunderstanding of the W3C Phase 2 RFC. The tracer must decode the `p` field, tag the span and propagate the `p` value whether it is valid or not.
> fix: W3C datadog `p` field propagation

- src/datadog/datadog_agent_config.cpp
- src/datadog/datadog_agent_config.h
- test/test_tracer_config.cpp
According to the Remote Configuration specification, `DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS` support floating point input and can be set to `0`.
System-tests use sub-seconds value for fast iteration. In order to test the library against remote configuration tests, the library must support sub-seconds inputs.
> fix: `DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS` support floating point input

- src/datadog/config_manager.cpp
- src/datadog/config_manager.h
- src/datadog/span_matcher.h
- src/datadog/trace_sampler.cpp
- src/datadog/trace_sampler.h
- src/datadog/trace_sampler_config.cpp
- src/datadog/trace_sampler_config.h
- test/test_tracer_config.cpp
Reset trace sampling rules legacy order.
> fix: trace sampling rules order

- src/datadog/extraction_util.cpp
- src/datadog/propagation_style.cpp
- src/datadog/propagation_style.h
- test/test_tracer.cpp
When the tracer encounters an invalid propagation header value, logging the list of headers and their values can lead to a crash.
For each key and value in the list of headers, a `nlohmann::json` instance is created with the following code:
```cpp
stream << nlohmann::json(it->first + ": " + it->second);
```
It is possible to craft an input for any of the headers inspected by the tracer that can cause a crash when the JSON library attempts to parse or dump the input.
> fix: prevent crash due to invalid headers

- src/datadog/extraction_util.cpp
- src/datadog/tracer.cpp
- test/test_tracer.cpp
This fixes a regression introduced by Sampling Delegation (#59). When the sampling delegation header is present during the trace context extraction, the sampling priority is discarded even if the feature is disabled.
This change of behaviour can potentially result in an increase of ingested spans. Additionnally, the tracer should behave as before the introduction of this feature when it is not enabled.
Changes:
- Sampling priority is not longer discard when `x-datadog-delegate-trace-sampling` is present.
- Update sampling delegation tests.
> fix: regression in sampling delegation handling

- CMakeLists.txt
- cmake/compiler/msvc.cmake
- cmake/deps/curl.cmake
- test/CMakeLists.txt
- Fix crash on macOS Sonoma: https://github.com/curl/curl/issues/11893
- Disable more curl features.
- Debug build do not enable sanitizers anymore.
- Fix usage of `BUILD_*_LIBS`
> deps: bump libcurl to 8.8.0

- src/datadog/extraction_util.cpp
- test/test_tracer.cpp
Fixed a regression introduced in issue #42  that prevented HTTP headers with leading spaces from being parsed. This issue could result in the failure to extract trace context and the creation of a new trace, even though the trace could have been extracted and continued in versions prior to v0.1.11.
> fix: trim inspected headers

- examples/http-server/proxy/proxy.cpp
- examples/http-server/server/server.cpp
- src/datadog/trace_segment.cpp
- src/datadog/trace_segment.h
- src/datadog/tracer.cpp
- src/datadog/tracer.h
- test/system-tests/request_handler.cpp
- test/test_tracer.cpp
Update the API:
- `extract_or_create_span` always returns a span, either the extracted one or a new span if the extraction fail.
- `override_sampling_priority` accepts `SamplingPriority`. 
`create_span` always returns a span, while `extract_span` may or may not return a span. Logically, one can think the behavior of `extract_or_create_span` should first attempt to `extract_span`, and if the extraction fails, it should then call `create_span`. At least, that's what the name of the function suggest and I think the desired behavior. 
The other one is for simplicity's sake.
> api: update the tracer api

- .circleci/config.yml
Per title
Python 3.9 won/t be supported by end of July in system-tests
> Switch system-tests to python 3.12

- src/datadog/extraction_util.cpp
- src/datadog/extraction_util.h
- src/datadog/tracer.cpp
- test/test_curl.cpp
- test/test_span.cpp
- test/test_tracer.cpp
Adds support for "W3C Phase 3" so that when multiple trace contexts are extracted (with the same trace-id) and the `tracecontext` format is used, the resulting trace context will have:
- `span.parent_id` set to the `tracecontext` parent-id value
- `span.tags["_dd.parent_id"]` set to either the value of `tracestate[dd][p]` or `hex(x-datadog-parent-id)`, in that order of precedence
> feat: ensure tracecontext headers take precedence over datadog (AIT-10281)

- src/datadog/remote_config/remote_config.cpp
- test/remote_config/test_remote_config.cpp
Fix bugs in remote config found during validation.
> fix: bugs in Remote Configuration payload construction

- bin/bazel-build
- bin/check
I just set up VSCode's clangd extension for C++ source browsing, and was giving it a test drive in dd-trace-cpp.
`bin/test` was failing on my machine due to changes needed in the build configuration of `test/system-tests`, and `bin/check` was failing due to changes needed to `bin/bazel-build`. At least on my machine.
If some of the helper scripts in `bin/` are no longer in use, it might be best to delete them. For now, I propose these changes to get things working again locally on my machine.
> patch some build/test scripts in `bin/`

- src/datadog/tracer_telemetry.cpp
- test/test_tracer_telemetry.cpp
Resolve a regression introduced in #130 where the `configuration_change` payload didn't adhere to the telemetry schema.
- Fix the regression.
- Validate top-level telemetry schema in unit tests.
> fix: telemetry `configuration_change` payload

- BUILD.bazel
Envoy was failing to build becase it couldn't locate the necessary headers in the `src` directory, even with the `-Isrc/datadog` flag. After investigating, I found that dd-trace-cpp srouce code is actually located at `external/com_github_datadog_dd_trace_cpp/src/datadog`. This means the correct include path should be `-Iexternal/com_github_datadog_dd_trace_cpp/src/datadog`. For some reson Bazel isn't able to handle this path expansion automatically.
After researching, it seems the recommended solution is to use the `includes` argument in `cc_library`. However, the Bazel documentation includes this warning:
> This should only be used for third-party libraries that do not conform to the Google style of writing #include statements. Unlike …
> chore(build): use `includes` argument in BUILD.bazel

- src/datadog/version.cpp
Our next release will be `v1.0.0` as part of our adherence to semantic versioning (semver). While there are no major changes, commits 32f0338 and d354e96 introduced some API changes that are not backward-compatible.
`v1.0.0` or `v0.3.0`? You decide.
> chore: bump version to v1.0.0

- .gitignore
- test/system-tests/main.cpp
- test/system-tests/request_handler.cpp
- test/system-tests/request_handler.h
Adds a new parametric test application endpoint `/trace/config` for retrieving the tracer configuration and fixes a small bug in the `/trace/span/start` handler when no service parameter is provided.
This allows the cpp tracer to run the test cases needed for conformance to our Config Consistency initiative
Jira ticket: [APMAPI-511] [APMAPI-516] [APMAPI-709]
[APMAPI-511]: https://datadoghq.atlassian.net/browse/APMAPI-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APMAPI-516]: https://datadoghq.atlassian.net/browse/APMAPI-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APMAPI-709]: https://datadoghq.atlassian.net/browse/APMAPI-709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> test: Update parametric tests for Config Consistency intiative

- src/datadog/platform_util.cpp
> fix: compilation issue for getting the process name

- src/datadog/tracer_telemetry.cpp
- src/datadog/tracer_telemetry.h
Keep a reference to user metrics to avoid dereferencing them when they are not alive anymore.
> fix: telemetry refactoring part 1

- include/datadog/telemetry/configuration.h
- src/datadog/telemetry/configuration.cpp
- src/datadog/tracer_config.cpp
- src/datadog/tracer_telemetry.cpp
- test/test_tracer_telemetry.cpp
That should solve [the failing system tests](https://app.circleci.com/pipelines/github/DataDog/dd-trace-cpp/1020/workflows/03748b2f-90d3-4192-a00f-ddb189d81e32/jobs/13419)
> fix: telemetry support for sub-seconds intervals

- CMakeLists.txt
Omit the 'curl' library if DD_TRACE_TRANSPORT is set to "none"
There is clearly the intent to be able to not include a default transport, by setting `DD_TRACE_TRANSPORT=none`.
However, two things were missing:
1. To ignore the bundled curl library from the build
2. to replace the `default_http_client_curl.cpp` with `default_http_client_null.cpp`
Integrations that provide their own transport may not want to build and link a whole unused library, along with any runtime library dependencies it makes.
> Properly support setting DD_TRACE_TRANSPORT to "none"

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- SECURITY.md
- adds a bug report and feature request issue template
- disables blank issue creation
- adds a security document
- standardizes the create issue experience across tracers
- see the [node.js create issue screen](https://github.com/DataDog/dd-trace-js/issues/new/choose) for an example of what this looks like
- does the C++ tracer instrument third party packages? I'm assuming not and have left such fields out
- let me know if there's any other things you need to know (musl, glibc, etc) and we can add fields
> chore: mandatory issue templates (AIDM-428)

- src/datadog/config_manager.cpp
- src/datadog/config_manager.h
- src/datadog/tracer.cpp
- test/test_config_manager.cpp
- test/test_datadog_agent.cpp
Removes the remote config check that asserts a matching env / service, as this is incorrectly causing remote config payloads to be ignored
This was motivated by a customer issue with adaptive sampling not working. When the tracer doesn't report an environment version but the Datadog agent does, incoming remote config payloads (which have already been verified by the Datadog agent) get rejected even though they are correct. This removes the validation and relies upon the Datadog agent verification.
The previous unit test has been removed as it's invalid, and the associated system-tests authored here have been tested locally with success: https://github.com/DataDog/system-tests/pull/3778
Jira ticket: [APMAPI-1006]
[APMAPI-1006]: https://datadoghq.atlassian.net/browse/APMAPI-1006?atlOrigin=ey …
> fix: Remote config service/env validation

- fuzz/w3c-propagation/fuzz.cpp
- src/datadog/w3c_propagation.cpp
- test/test_tracer.cpp
`std::regex` is [notoriously known to be slow](https://github.com/HFTrader/regex-performance?tab=readme-ov-file#results). This custom parser implementation offers significantly better performance.
Bench: https://quick-bench.com/q/XJw86Zh_SBDpQ3xhI2nrY-k-Xbc
Result:
> perf: parse w3c traceparent using a customer parser

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- **Add dependabot for github actions**
- **Pin all actions by hash**
Pinning 3rd-party GitHub Actions by commit SHA makes them less vulnerable to compromise of the 3rd party. To avoid outdating and non-verbosity, versions are commented after the SHA and updating via dependabot is introduced that will automatically update the commented version tag as well.
In case of a false commit SHA, this change could break the corresponding workflow. Typically, this does not cause major interruptions, but it can for example affect a release pipeline and require restart causing delays.
> ci: pin github actions by hash and update via dependabot

- .circleci/config.yml
Also store test results in circleci.
> chore(ci): add datadog test optimization

- src/datadog/datadog_agent.cpp
- src/datadog/tracer_telemetry.cpp
- src/datadog/tracer_telemetry.h
- test/test_tracer_telemetry.cpp
This fix addresses two issues:
1. Prevents invalid telemetry payloads when there are no configuration entries.
2. Ensures configuration updates are correctly processed and not carried over to the next update.
> fix(telemetry): Handle empty configuration payload properly

- include/datadog/tracer.h
- src/datadog/platform_util.cpp
- src/datadog/platform_util.h
- src/datadog/random.cpp
- src/datadog/random.h
- src/datadog/tracer.cpp
Resolves [APMAPI-1066]
[APMAPI-1066]: https://datadoghq.atlassian.net/browse/APMAPI-1066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: store tracer configuration in an in-memory file

- .circleci/config.yml
- CMakePresets.json
- src/datadog/string_util.cpp
- src/datadog/w3c_propagation.cpp
- test/CMakeLists.txt
- test/mocks/collectors.h
- test/mocks/loggers.h
- test/remote_config/test_remote_config.cpp
- test/system-tests/utils.h
- test/test.cpp
- test/test.h
- test/test_span.cpp
- test/test_span_sampler.cpp
- test/test_trace_sampler.cpp
- test/test_trace_segment.cpp
- test/test_tracer.cpp
- test/test_tracer_config.cpp
- test/test_tracer_telemetry.cpp
Fix warnings.
Changes:
- Treat warnings as error in CI builds for MSVC.
> chore(msvc): fix compilation warnings

- doc/maintainers.md
- include/datadog/cerr_logger.h
- include/datadog/tracer_config.h
- test/test_cerr_logger.cpp
Commit [9f7d0aa0a82795f8a5a134b4b44332955360d43a][1] introduced `NullLogger` as the default logger, replacing `CerrLogger`.
This revision updates some relevant documentation.
I used `git grep CerrLogger` and [check-markdown-links][2] to find the mismatches.
[1]: https://github.com/DataDog/dd-trace-cpp/commit/9f7d0aa0a82795f8a5a134b4b44332955360d43a
[2]: https://github.com/dgoffredo/check-markdown-links
> chore: document that `NullLogger` is the default

- .circleci/config.yml
- .github/workflows/codeql-analysis.yml
- CMakePresets.json
The CI started fails recently because chocolatey and ubuntu-latest install the latest version of CMake (4.0.0), which remove compatibility with CMake < 3.5. Until we update the CMake version (and because it's good pratice), pin the version of CMake to 3.31.6 which is still compatible with 3.5 and older.
Changes:
- Add a new cmake preset for codeql.
> chore(ci): pin cmake version

- include/datadog/datadog_agent_config.h
- include/datadog/telemetry/telemetry.h
- include/datadog/trace_segment.h
- include/datadog/tracer.h
- include/datadog/tracer_config.h
- src/datadog/config_manager.cpp
- src/datadog/config_manager.h
- src/datadog/datadog_agent.cpp
- src/datadog/datadog_agent.h
- src/datadog/telemetry/telemetry.cpp
- src/datadog/trace_segment.cpp
- src/datadog/tracer.cpp
- src/datadog/tracer_config.cpp
- src/datadog/tracer_telemetry.cpp
- src/datadog/tracer_telemetry.h
- test/CMakeLists.txt
- test/mocks/http_clients.h
- test/telemetry/test_telemetry.cpp
- test/test_config_manager.cpp
- test/test_datadog_agent.cpp
This PR continues the work of refactoring the telemetry module to provide a clear and structured telemetry API. The goal is to make it easier for Datadog engineers to collect telemetry metrics and logs on the usage of our products.
Specifically, this PR moves the telemetry logic out of `DatadogAgent` and into a the telemetry module.
For reference, Part 1 of this refactoring can be found here: [#166](https://github.com/DataDog/dd-trace-cpp/pull/166).
> [part 2] refactor!(telemetry): move telemetry logic from `DatadogAgent`

- BUILD.bazel
- CMakeLists.txt
- include/datadog/telemetry/metrics.h
- include/datadog/telemetry/telemetry.h
- include/datadog/trace_segment.h
- include/datadog/tracer.h
- src/datadog/config_manager.cpp
- src/datadog/config_manager.h
- src/datadog/datadog_agent.cpp
- src/datadog/datadog_agent.h
- src/datadog/telemetry/telemetry.cpp
- src/datadog/telemetry/telemetry_impl.cpp
- src/datadog/telemetry/telemetry_impl.h
- src/datadog/trace_segment.cpp
- src/datadog/tracer.cpp
- test/telemetry/test_telemetry.cpp
- test/test_config_manager.cpp
- test/test_datadog_agent.cpp
This is Part 3 of the telemetry module refactoring. This PR introduces a singleton for the telemetry module, allowing external usage outside of the tracer API while ensuring all components access the same instance. Additionally, this change simplifies internal telemetry usage.  
For reference:  
- **Part 1:** #166
- **Part 2:** #194
> [part 3] refactor!(telemetry): introduce a singleton

- src/datadog/telemetry/telemetry_impl.cpp
- test/telemetry/test_telemetry.cpp
Previously, telemetry metrics were collected every 10 seconds and heartbeats were sent every 60 seconds, matching the default configuration. However, these intervals can be customized via environment variables or code.
This commit updates the telemetry logic to use the configured intervals—whether set through environment variables or directly in the code—ensuring that metrics , heartbeat and logs messages are sent accordingly.
> [part 5] refactor!(telemetry): use configured intervals

- include/datadog/telemetry/telemetry.h
- src/datadog/telemetry/telemetry.cpp
- src/datadog/telemetry/telemetry_impl.cpp
- src/datadog/telemetry/telemetry_impl.h
- test/telemetry/test_telemetry.cpp
Changes:
- Update telemetry API for logs to be consistent with metrics.
- Add test to validate logs are send in `app-closing`.
> fix(telemetry): report logs only once

- src/datadog/curl.cpp
- test/test_curl.cpp
The telemetry refactoring exposed high mutex contention in our NGINX integration during shutdown/reload phase. This commit addresses mutex contention in the curl integration used by the default http client.
> perf: improve mutex contention

- src/datadog/curl.cpp
- src/datadog/telemetry/telemetry_impl.cpp
- test/test_curl.cpp
Fix the issue reported in #213.
`make_telemetry` initializes a `Telemetry` object, which is then "moved" via the move constructor. During construction, the `Telemetry` constructor makes an asynchronous HTTP request for the `app-started` event.
If this request is not processed before the move occurs, the lambda callback associated with the request reference the original (now-invalid) object. This results in a dangling pointer access and leads to a crash 💥.
The fix enhance the drain mechanism by canceling/removing requests in-flight. This ensures that any in-flight requests are resolved or cleared before the object is moved or destroyed, avoiding use-after-move scenarios.
> fix(curl): enforce drain to clear in-flight requests

- src/datadog/telemetry/telemetry.cpp
- src/datadog/telemetry/telemetry_impl.cpp
- src/datadog/telemetry/telemetry_impl.h
This addresses a regression introduced in #205 that caused a noticeable delay during the first initialization of the library.
> fix(telemetry): send app-started asynchronously

- include/datadog/telemetry/telemetry.h
- src/datadog/telemetry/telemetry.cpp
- src/datadog/telemetry/telemetry_impl.cpp
- src/datadog/telemetry/telemetry_impl.h
- src/datadog/tracer.cpp
- src/datadog/tracer_config.cpp
- test/telemetry/test_telemetry.cpp
This fixes a regression introduced during the telemetry module refactoring. When the telemetry module is initialized in the tracer context, it now correctly uses the tracer's service name, environment, and runtime ID to ensure consistency.
Changes:
- fix reported baggage configuration values.
> fix(telemetry): use tracer's service, env and runtime ID

- .gitlab/benchmarks.yml
Disables FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY that we used before to ensure build containers have QoS guaranteed. As of now, it doesn't seem to be necessary anymore, but leads to problems like https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4119.
Fix issue with GItlab CI jobs silently randomly failing with a green status.
> fix(ci): disable legacy Gitlab exec in order to fix jobs failing with green status

- .gitlab/benchmarks.yml
Adding documentation for PR-level gate following the provided [template](https://datadoghq.atlassian.net/wiki/spaces/~712020d6ebcb0430fe403fb49051da60de7870/pages/5328339593/PR-level+gates+and+Pre-release+Gates+Documentation+Templates).
> chore(gates): add a comment to explain PR quality gates

- cmake/deps/json.cmake
Add `FIND_PACKAGE_ARGS` will help `FetchContent_*` to satisfy the dependency with `find_package()`. If that dependency is not found, then it is built from source.
Supersede: #227 
Close #227 
Bump version of nlohmann_json to 3.12.0.
> deps(nlohmann-json): `FetchContent` rely on `find_package`

- src/datadog/telemetry_metrics.cpp
- src/datadog/telemetry_metrics.h
- src/datadog/tracer.cpp
- adds telemetry metric for malformed headers (specifically for baggage)
> feat(telemetry): report malformed baggage header 
